### ISSUE TITLE
Short-term TODO

### ISSUE THREAD

**Issue by mariusnita** [hyperdiv/hyperdiv#15]
Stuff to add in the near future:

* [x] Add Shoelace [tree component](https://shoelace.style/components/tree)
* [ ] File upload component
* [ ] Support for math formulas in Markdown #3 
* [x] Audio component #13 
* [x] Video component
* [x] Popup component
* [ ] High performance grid component (e.g., https://www.ag-grid.com)
* [x] Support for matplotlib charts
* [ ] Support for plotly charts
* [ ] Support for additional icon libraries and SVG sheets

**Comment by qiuwei** [comment]
Hope you can add support for [Altair](https://altair-viz.github.io/) as well.
It is an elegantly designed plotting library.

**Comment by jacoverster** [comment]
Hi there, great job on this framework! Do you perhaps have a timeline on the File Upload component?

**Comment by mariusnita** [comment]
Hi, no concrete timeline for file upload yet. Any specific features / ideas you have in mind for this component?

**Comment by jacoverster** [comment]
Hi @mariusnita, no specific ideas - my project is currently using the Streamlit file_uploader. I don't think features like drag-n-drop or filetype filtering are needed to start with. I'm happy to help with this if you can provide some guidance.

**Comment by mariusnita** [comment]
I started investigating. Currently leaning toward quickly building a basic `<input type="file">` uploader. Maybe in the future we can add support for Dropzone or other feature-rich frontend upload modules. Those could be built as plugins, as well.

**Comment by jacoverster** [comment]
That sounds good. Thanks and let me know if I can help with anything.

**Comment by vladignatyev** [comment]
"Support for additional icons" looks like a good first issue. I'll take it!
